### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [Lucasybanez/RollingGourmeteBack#1]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/Lucasybanez/RollingGourmeteBack/assets/53904695/0e4aface-c2f6-4b78-8efd-787affa35246)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Lucasybanez** [comment]
**Solucionado**
